### ISSUE TITLE
Hurl 4.1.0 does not install

### ISSUE THREAD

**Issue by rgreinho** [gacts/install-hurl#61]
Starting at the 4.1.0 release of [Hurl](https://github.com/Orange-OpenSource/hurl/releases/tag/4.1.0), the names of the assets attached to the GitHub Release changed, causing the download of the binary to fail.

<img width="542" alt="image" src="https://github.com/gacts/install-hurl/assets/6969134/02f8c1d1-ee79-45e7-b5db-4a0301e5ad53">

**Comment by tarampampam** [comment]
Thank you for your report, a fixed release was published!
