### ISSUE TITLE
Hurl restructured tarball

### ISSUE THREAD

**Issue by otteroledyer** [gacts/install-hurl#78]
The script fails to install with latest version, resulting in the following error:
`Error: Unable to locate executable file: hurl. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`

Here is the issue for hurl:
https://github.com/Orange-OpenSource/hurl/issues/2401

**Comment by aimagineapp** [comment]
Getting the same here.

**Comment by tarampampam** [comment]
Got it, thanks. A fix will be implemented shortly

**Comment by tarampampam** [comment]
A fixed version has been published under the tag `v1.1.1` (as well as `v1.1` and `v1`). If you were using the `v1` version previously, you don't need to make any changes on your end. Simply rerun the failed actions.

**Comment by tarampampam** [comment]
Important note: You need to remove the cached `hurl` from your repository's actions cache. To do that, simply open the page `https://github.com/<org>/<repo>/actions/caches`, find every cache item with a name containing `hurl`, and remove them. That's it!
